### ISSUE TITLE
User Story #14 Button for Input

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/Geschenkezeit#16]
## Value Proposition

**As a** user

**I want to** have a button to open the input field

**to be able to** have a bigger view of the birthday list.

## Description

![Image](https://user-images.githubusercontent.com/115352305/211387547-1f5757cb-e06f-4b4b-aa23-284d6f6f0f7e.png)

## Acceptance Criteria

- [ ] There is a button.
- [ ] The button opens the input field.
- [ ] Adding info in the input field add them to the list.

## Tasks

- [ ] new branch: feature/button-for-input
- [ ] add button
- [ ] connect input field with button
- [ ] make info appear in list
- [ ] make input field disappear after submitting
