### ISSUE TITLE
User Story #6 Profile Page

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/Geschenkezeit#7]
## Value Proposition

**As a** user
**I want to** see more info about each person's birthday
**to be able to** plan the birthday present better.

## Description

![Image](https://user-images.githubusercontent.com/115352305/208409526-ab83c994-cd07-48dc-875c-038f2d83c595.png)

## Acceptance Criteria

- [x] After clicking on a name, a profile page is opened.
- [x] The profile page shows the previously added ideas.
- [x] The profile page gives information about the age and in how many days the birthday will be.
- (there will be more options to add to the profile page in the future)

## Tasks

- [x] new branch: feature/profile-page
- [x] create profile page where age and days until the birthday are calculated and all existing info is included
- [x] make each person clickable as a button
- [x] link entry to profile page

**Comment by esrefbozkurt** [comment]
Are the ideas and bday editable on this page? My idea is to make the whole container clickable.
Nice structure. I like the way your think! :)

**Comment by AntjeWalter** [comment]
Yes, right now each container can be edited. I will try to make the whole container clickable but as a fallback option I would only make the name clickable.
