### ISSUE TITLE
User Story #7 Info about person

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/Geschenkezeit#8]
## Value Proposition

**As a** user
**I want to** add more information about the person
**to be able to** get more ideas about possible presents.

## Description

![Image](https://user-images.githubusercontent.com/115352305/208417198-2dad392a-1f08-4488-abb1-9fbd645167fd.png)

## Acceptance Criteria

- [ ] There is an option to add favorite things.
- [ ] There is an option to add things the person dislikes.

## Tasks

- [x] new branch: feature/more-info
- [x] add headlines
- [x] add input possibility to each headline
- [x] add info to array of objects

**Comment by JanRaadts** [comment]
maybe another task is it, to add the new information to the array? :)

**Comment by AntjeWalter** [comment]
Good hint, thanks!

**Comment by AntjeWalter** [comment]
I changed my US from two input fields to just one, where you can leave general comments and info about the person :)
