### ISSUE TITLE
User Story #8 More Ideas

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/Geschenkezeit#9]
## Value Proposition

**As a** user
**I want to** see more info about each person's birthday
**to be able to** plan the birthday present better.

## Description

![Image](https://user-images.githubusercontent.com/115352305/208416747-d3eb0d1f-0a9c-4cc6-8b39-c1a78ce23456.png)

## Acceptance Criteria

- [x] The ideas can be edited on the profile page.
- [x] The ideas change on the list-page after editing on profile page.

## Tasks

- [x] new branch: feature/more-ideas
- [x] add input option to ideas
- [x] make list-page change after submitting input
